### ISSUE TITLE
Binary (Windows) release?

### ISSUE THREAD

**Issue by oscarbg** [Pierre-Terdiman/PEEL_PhysX_Edition#10]

**Comment by Pierre-Terdiman** [comment]
There is a Windows binary there. What is the question?

**Comment by oscarbg** [comment]
ah sorry, my wrong..
I quick looked for something in either:
https://github.com/Pierre-Terdiman/PEEL_PhysX_Edition/releases
or:
https://github.com/Pierre-Terdiman/PEEL_PhysX_Edition/tags
closing..
