### ISSUE TITLE
PhysX 5.5 support?

### ISSUE THREAD

**Issue by oscarbg** [Pierre-Terdiman/PEEL_PhysX_Edition#12]
Hi,
seems it just got released.. or doesn't bring any perf improvements vs shipped 5.4.2?
thanks..

**Comment by Pierre-Terdiman** [comment]
Yes, I will add a 5.5.0 plugin as well. I think it has a few more features and bug fixes but no clear perf (CPU) improvements.

**Comment by Pierre-Terdiman** [comment]
Done!
